// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb_omkyocDph72N-mUw1jx-1Bltwq0BRw',
    appId: '1:842154392335:web:6221ffc13c3e93a8045c7a',
    messagingSenderId: '842154392335',
    projectId: 'notify-d5ab1',
    authDomain: 'notify-d5ab1.firebaseapp.com',
    storageBucket: 'notify-d5ab1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVohh2FP8435L-9rGwpJ50gA1m1INuJBE',
    appId: '1:842154392335:android:74573d1195976c57045c7a',
    messagingSenderId: '842154392335',
    projectId: 'notify-d5ab1',
    storageBucket: 'notify-d5ab1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVaw0EBCZS_ldKfOxTU06h7JrivL_IbUU',
    appId: '1:842154392335:ios:77090243a8469957045c7a',
    messagingSenderId: '842154392335',
    projectId: 'notify-d5ab1',
    storageBucket: 'notify-d5ab1.firebasestorage.app',
    iosBundleId: 'com.example.notify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVaw0EBCZS_ldKfOxTU06h7JrivL_IbUU',
    appId: '1:842154392335:ios:77090243a8469957045c7a',
    messagingSenderId: '842154392335',
    projectId: 'notify-d5ab1',
    storageBucket: 'notify-d5ab1.firebasestorage.app',
    iosBundleId: 'com.example.notify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb_omkyocDph72N-mUw1jx-1Bltwq0BRw',
    appId: '1:842154392335:web:2564fb64c1a31777045c7a',
    messagingSenderId: '842154392335',
    projectId: 'notify-d5ab1',
    authDomain: 'notify-d5ab1.firebaseapp.com',
    storageBucket: 'notify-d5ab1.firebasestorage.app',
  );
}
